# New Red Bull API

Championship tables

In [1]:
%run wrc_rallydj/livetiming_api2.py

In [2]:
wrc = WRCTimingResultsAPIClientV2(newDB=True)

INFO:__main__:Initialising the database...
INFO:__main__:Creating new db tables...

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/seasons.json

INFO:__main__:Upserting seasons...

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/season-detail.json?seasonId=34

INFO:__main__:Upserting championship_lookup...
INFO:__main__:Upserting season_rounds...

In [3]:
wrc.setEventByName("Rally Sweden")
wrc.eventId, wrc.eventName, wrc.year

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/events/535.json

INFO:__main__:Upserting event_classes...
INFO:__main__:Upserting event_rallies...
INFO:__main__:Upserting event_date...

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/events/535/stages.json

INFO:__main__:Upserting stage_info...
INFO:__main__:Upserting split_points...
INFO:__main__:Upserting stage_controls...
INFO:__main__:Upserting meta_completed_event_tables...
INFO:__main__:Upserting meta_completed_event_tables...
INFO:__main__:Upserting meta_completed_event_tables...

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/events/535/rallies/583/entries.json

INFO:__main__:Upserting entries...
INFO:__main__:Upserting entries_drivers...
INFO:__main__:Upserting entries_codrivers...
INFO:__main__:Upserting groups...
INFO:__main__:Upserting manufacturers...
INFO:__main__:Upserting entrants...

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/events/535/itineraries/1137.json

INFO:__main__:Upserting itinerary_legs...
INFO:__main__:Upserting itinerary_stages...
INFO:__main__:Upserting itinerary_sections...
INFO:__main__:Upserting itinerary_controls...

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/events/535/startLists/1810.json

INFO:__main__:Upserting startlists...

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/events/535/startLists/1811.json

INFO:__main__:Upserting startlists...

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/events/535/startLists/1813.json

INFO:__main__:Upserting startlists...

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/events/535/startLists/1815.json

INFO:__main__:Upserting startlists...

(535, 'Rally Sweden', 2025)

In [5]:
# The championshipId gives an identifier for a particular championshp
# The seasonId can be used to identify champiohsips for a season
# The seasonId is different for WRC and ERC
# We have wrc|erc in wrc.championship set from:
# wrc.championship = wrc.CHAMPIONSHIP_CODES[wrc.championshipLookup[seasonId]]
# Get championshipId from seasonId as:
# SELECT FROM championship_lookup AS cl WHERE cl.seasonId={seasonId}
wrc.getChampionships()

,championshipId,name,seasonId,type,fieldOneDescription,fieldTwoDescription,fieldThreeDescription,fieldFiveDescription,fieldFourDescription
0,287,FIA World Rally Championship for Drivers,34,Drivers,FirstName,LastName,CountryISO3,ManufacturerFull,Manufacturer
1,288,FIA World Rally Championship for Co-Drivers,34,Codrivers,FirstName,LastName,CountryISO3,TyreManufacturer,Manufacturer
2,289,FIA World Rally Championship for Manufacturers,34,Manufacturer,Name,Manufacturer,LogoFileName,,
3,290,FIA World Rally Championship for Teams,34,Manufacturer,Name,Manufacturer,LogoFileName,,
4,291,FIA WRC2 Championship for Drivers,34,DriversWithEntrant,FirstName,LastName,CountryISO3,Entrant,Manufacturer
5,292,FIA WRC2 Championship for Co-Drivers,34,CodriversWithEntrant,FirstName,LastName,CountryISO3,Entrant,Manufacturer
6,293,FIA WRC2 Challenger Championship for Drivers,34,DriversWithEntrant,FirstName,LastName,CountryISO3,Entrant,Manufacturer
7,294,FIA WRC2 Challenger Championship for Co-Drivers,34,CodriversWithEntrant,FirstName,LastName,CountryISO3,Entrant,Manufacturer
8,295,FIA WRC2 Championship for Teams,34,Manufacturer,Name,Manufacturer,LogoFileName,,
9,296,FIA WRC Masters Cup for Drivers,34,DriversWithEntrant,FirstName,LastName,CountryISO3,Entrant,Manufacturer
10,297,FIA WRC Masters Cup for Co-Drivers,34,CodriversWithEntrant,FirstName,LastName,CountryISO3,Entrant,Manufacturer
11,298,FIA WRC3 Championship for Drivers,34,DriversWithEntrant,FirstName,LastName,CountryISO3,Entrant,Manufacturer
12,299,FIA WRC3 Championship for Co-Drivers,34,CodriversWithEntrant,FirstName,LastName,CountryISO3,Entrant,Manufacturer
13,300,FIA Junior WRC Championship for Drivers,34,DriversWithEntrant,FirstName,LastName,CountryISO3,Entrant,Manufacturer
14,301,FIA Junior WRC Championship for Co-Drivers,34,CodriversWithEntrant,FirstName,LastName,CountryISO3,Entrant,Manufacturer

In [6]:
wrc.setChampionship()
wrc.championshipId, wrc.championshipName

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/championship-overall-results.json?championshipId=287&seasonId=34

INFO:__main__:Inserting championship_overall (if_exists: append)...
INFO:__main__:Upserting championship_results...

https://p-p.redbull.com/rb-wrccom-lintegration-yv-prod/api/championship-detail.json?championshipId=287&seasonId=34

INFO:__main__:Upserting championship_rounds_detail...
INFO:__main__:Upserting championship_countries...
INFO:__main__:Upserting championship_entries...

(np.int64(287), 'FIA World Rally Championship for Drivers')

In [7]:
wrc.getChampionshipByRound(on_season=True, raw=False)

,championshipEntryId,championshipId,seasonId,dropped,eventId,pointsBreakdown,position,publishedStatus,status,totalPoints,entryId,LastName,eventName,startDate,Round,finishDate
0,6699,287,34,0,534,25 + 3 + 5,1,Published,Finished,33,None,OGIER,Rallye Monte-Carlo,2025-01-23,1,2025-01-26
1,6700,287,34,0,534,17 + 5 + 4,2,Published,Finished,26,None,EVANS,Rallye Monte-Carlo,2025-01-23,1,2025-01-26
2,6701,287,34,0,534,15 + 2 + 3,3,Published,Finished,20,None,FOURMAUX,Rallye Monte-Carlo,2025-01-23,1,2025-01-26
3,6698,287,34,0,534,12 + 4 + 2,4,Published,Finished,18,None,ROVANPERÄ,Rallye Monte-Carlo,2025-01-23,1,2025-01-26
4,6697,287,34,0,534,10 + 0 + 1,5,Published,Finished,11,None,TÄNAK,Rallye Monte-Carlo,2025-01-23,1,2025-01-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,6838,287,34,0,536,-,-,Published,DidNotEnter,0,None,KORHONEN,Safari Rally Kenya,2025-03-20,3,2025-03-23
59,6706,287,34,0,536,-,-,Published,DidNotEnter,0,None,CAMILLI,Safari Rally Kenya,2025-03-20,3,2025-03-23
60,6840,287,34,0,536,-,-,Published,DidNotEnter,0,None,BERTELLI,Safari Rally Kenya,2025-03-20,3,2025-03-23
61,6698,287,34,0,536,R,R,Published,RetiredMechanical,0,None,ROVANPERÄ,Safari Rally Kenya,2025-03-20,3,2025-03-23
62,6784,287,34,0,536,R,R,Published,RetiredMechanical,0,None,KATSUTA,Safari Rally Kenya,2025-03-20,3,2025-03-23

In [40]:
wrc.getDrivers(by_championship=True)

,personId,countryId,state,firstName,lastName,abbvName,fullName,code,licenseNumber,country.countryId,country.name,country.iso2,country.iso3
0,762,22,None,Thierry,NEUVILLE,T. NEUVILLE,Thierry NEUVILLE,NEU,None,22,Belgium,BE,BEL
1,534,235,None,Elfyn,EVANS,E. EVANS,Elfyn EVANS,EVA,None,235,United Kingdom,GB,GBR
2,524,70,None,Ott,TÄNAK,O. TÄNAK,Ott TÄNAK,TÄN,None,70,Estonia,EE,EST
3,4676,76,None,Adrien,FOURMAUX,A. FOURMAUX,Adrien FOURMAUX,FOU,None,76,France,FR,FRA
4,785,112,None,Takamoto,KATSUTA,T. KATSUTA,Takamoto KATSUTA,KAT,None,112,Japan,JP,JPN
5,700,75,None,Kalle,ROVANPERÄ,K. ROVANPERÄ,Kalle ROVANPERÄ,ROV,None,75,Finland,FI,FIN
6,5279,130,None,Grégoire,MUNSTER,G. MUNSTER,Grégoire MUNSTER,MUN,None,130,Luxembourg,LU,LUX
7,5280,75,None,Sami,PAJARI,S. PAJARI,Sami PAJARI,PAJ,None,75,Finland,FI,FIN
8,3169,301,None,Mārtinš,SESKS,M. SESKS,Mārtinš SESKS,SES,None,301,Latvia IOC,LV,LAT
9,5791,107,None,Joshua,MCERLEAN,J. MCERLEAN,Joshua MCERLEAN,MCE,None,107,Ireland,IE,IRL
10,774,110,None,Lorenzo,BERTELLI,L. BERTELLI,Lorenzo BERTELLI,BER,None,110,Italy,IT,ITA
11,3125,300,None,Jourdan,SERDERIDIS,J. SERDERIDIS,Jourdan SERDERIDIS,SER,None,300,Greece IOC,GR,GRE
12,5357,215,None,Oliver,SOLBERG,O. SOLBERG,Oliver SOLBERG,SOL,None,215,Sweden,SE,SWE
13,9102,75,None,Roope,KORHONEN,R. KORHONEN,Roope KORHONEN,KOR,None,75,Finland,FI,FIN
14,4776,305,None,Fabrizio,ZALDIVAR,F. ZALDIVAR,Fabrizio ZALDIVAR,ZAL,None,305,Paraguay IOC,PY,PAR

In [41]:
wrc.getChampionshipOverall()

    championshipEntryId  overallPosition  overallPoints
0                  6700                1             88
1                  6702                2             52
2                  6697                3             49
3                  6699                4             33
4                  6701                5             31
5                  6698                6             31
6                  6784                7             25
7                  6782                8             19
8                  6783                9             16
9                  6836               10              8
10                 6985               11              8
11                 6703               12              8
12                 6986               13              6
13                 6704               14              4
14                 6839               15              4
15                 6987               16              2
16                 6705               17              2
17                 6837               18              2
18                 6838               19              1
19                 6706               20              1
20                 6840               21              0

In [ ]:
# -[ ] TO DO - add a Round column to the not raw championship tables
# -[ ] TO DO - add a posChange column (for SS1, this is 0); going 2 to 1 is +1;
# -[ ] TO DO - add further annotations: leadStatus: None is NA, -1 lost lead; 0 retained lead; 1 gained lead; (changedLead is then bool(leadStatus))
# TO DO the same change logic can be used in events for mapping overall rally lead changes etc


# TO DO championship progression; see what we can reuse from tally progression;

False

In [42]:
# In the annotated table, we can get the driver name and driver code
# TO DO also get the car number
wrc.getChampionshipOverall(raw=False)

,championshipEntryId,overallPosition,overallPoints,driverCode,driverName
0,6700,1,88,EVA,Elfyn EVANS
1,6702,2,52,NEU,Thierry NEUVILLE
2,6697,3,49,TÄN,Ott TÄNAK
3,6701,5,31,FOU,Adrien FOURMAUX
4,6698,6,31,ROV,Kalle ROVANPERÄ
5,6784,7,25,KAT,Takamoto KATSUTA
6,6782,8,19,PAJ,Sami PAJARI
7,6783,9,16,MUN,Grégoire MUNSTER
8,6836,10,8,SES,Mārtinš SESKS
9,6703,12,8,MCE,Joshua MCERLEAN
10,6839,15,4,SER,Jourdan SERDERIDIS
11,6987,16,2,ZAL,Fabrizio ZALDIVAR
12,6837,18,2,SOL,Oliver SOLBERG
13,6838,19,1,KOR,Roope KORHONEN
14,6840,21,0,BER,Lorenzo BERTELLI

In [ ]:
# The points awarded for a particular round of a partciular championship
wrc.getChampionshipByRound()
# TO DO - the entryId is missing; should we try to map this somehow?
# TO DO  - where do we get total championship points at the end of a round?

,championshipEntryId,championshipId,dropped,eventId,pointsBreakdown,position,publishedStatus,status,totalPoints,entryId
0,6700,287,0,535,25 + 5 + 5,1,Published,Finished,35,None
1,6700,287,0,536,25 + 2,1,Published,Finished,27,None
2,6700,287,0,534,17 + 5 + 4,2,Published,Finished,26,None
3,6702,287,0,536,15 + 4 + 4,3,Published,Finished,23,None
4,6702,287,0,535,15 + 2 + 3,3,Published,Finished,20,None
...,...,...,...,...,...,...,...,...,...,...
58,6706,287,0,536,-,-,Published,DidNotEnter,0,None
59,6706,287,0,535,-,-,Published,DidNotEnter,0,None
60,6840,287,0,536,-,-,Published,DidNotEnter,0,None
61,6840,287,0,534,-,-,Published,DidNotEnter,0,None
62,6840,287,0,535,D,D,Published,DidNotStart,0,None

In [44]:
# In the annotated view, raw=False,
# we bring in the driver name and code from championshipId,
# the round name from eventId
wrc.getChampionshipByRound(raw=False)

,championshipEntryId,championshipId,dropped,eventId,pointsBreakdown,position,publishedStatus,status,totalPoints,entryId,driverCode,driverName,eventName,startDate,finishDate
0,6700,287,0,535,25 + 5 + 5,1,Published,Finished,35,None,EVA,Elfyn EVANS,Rally Sweden,2025-02-13,2025-02-16
1,6700,287,0,536,25 + 2,1,Published,Finished,27,None,EVA,Elfyn EVANS,Safari Rally Kenya,2025-03-20,2025-03-23
2,6700,287,0,534,17 + 5 + 4,2,Published,Finished,26,None,EVA,Elfyn EVANS,Rallye Monte-Carlo,2025-01-23,2025-01-26
3,6702,287,0,536,15 + 4 + 4,3,Published,Finished,23,None,NEU,Thierry NEUVILLE,Safari Rally Kenya,2025-03-20,2025-03-23
4,6702,287,0,535,15 + 2 + 3,3,Published,Finished,20,None,NEU,Thierry NEUVILLE,Rally Sweden,2025-02-13,2025-02-16
5,6702,287,0,534,8 + 1,6,Published,Finished,9,None,NEU,Thierry NEUVILLE,Rallye Monte-Carlo,2025-01-23,2025-01-26
6,6697,287,0,536,17 + 3 + 3,2,Published,Finished,23,None,TÄN,Ott TÄNAK,Safari Rally Kenya,2025-03-20,2025-03-23
7,6697,287,0,535,12 + 3,4,Published,Finished,15,None,TÄN,Ott TÄNAK,Rally Sweden,2025-02-13,2025-02-16
8,6697,287,0,534,10 + 0 + 1,5,Published,Finished,11,None,TÄN,Ott TÄNAK,Rallye Monte-Carlo,2025-01-23,2025-01-26
9,6701,287,0,534,15 + 2 + 3,3,Published,Finished,20,None,FOU,Adrien FOURMAUX,Rallye Monte-Carlo,2025-01-23,2025-01-26
10,6701,287,0,536,0 + 5 + 5,16,Published,Finished,10,None,FOU,Adrien FOURMAUX,Safari Rally Kenya,2025-03-20,2025-03-23
11,6701,287,0,535,0 + 0 + 1,40,Published,Finished,1,None,FOU,Adrien FOURMAUX,Rally Sweden,2025-02-13,2025-02-16
12,6698,287,0,534,12 + 4 + 2,4,Published,Finished,18,None,ROV,Kalle ROVANPERÄ,Rallye Monte-Carlo,2025-01-23,2025-01-26
13,6698,287,0,535,10 + 1 + 2,5,Published,Finished,13,None,ROV,Kalle ROVANPERÄ,Rally Sweden,2025-02-13,2025-02-16
14,6698,287,0,536,R,R,Published,RetiredMechanical,0,None,ROV,Kalle ROVANPERÄ,Safari Rally Kenya,2025-03-20,2025-03-23
15,6784,287,0,535,17 + 4 + 4,2,Published,Finished,25,None,KAT,Takamoto KATSUTA,Rally Sweden,2025-02-13,2025-02-16
16,6784,287,0,536,R,R,Published,RetiredMechanical,0,None,KAT,Takamoto KATSUTA,Safari Rally Kenya,2025-03-20,2025-03-23
17,6784,287,0,534,R,R,Published,RetiredAccident,0,None,KAT,Takamoto KATSUTA,Rallye Monte-Carlo,2025-01-23,2025-01-26
18,6782,287,0,536,12 + 0 + 1,4,Published,Finished,13,None,PAJ,Sami PAJARI,Safari Rally Kenya,2025-03-20,2025-03-23
19,6782,287,0,535,6 + 0,7,Published,Finished,6,None,PAJ,Sami PAJARI,Rally Sweden,2025-02-13,2025-02-16
20,6782,287,0,534,R,R,Published,RetiredAccident,0,None,PAJ,Sami PAJARI,Rallye Monte-Carlo,2025-01-23,2025-01-26
21,6783,287,0,536,10 + 0 + 2,5,Published,Finished,12,None,MUN,Grégoire MUNSTER,Safari Rally Kenya,2025-03-20,2025-03-23
22,6783,287,0,535,4 + 0,8,Published,Finished,4,None,MUN,Grégoire MUNSTER,Rally Sweden,2025-02-13,2025-02-16
23,6783,287,0,534,R,R,Published,RetiredAccident,0,None,MUN,Grégoire MUNSTER,Rallye Monte-Carlo,2025-01-23,2025-01-26
24,6836,287,0,535,8 + 0,6,Published,Finished,8,None,SES,Mārtinš SESKS,Rally Sweden,2025-02-13,2025-02-16
25,6836,287,0,536,-,-,Published,DidNotEnter,0,None,SES,Mārtinš SESKS,Safari Rally Kenya,2025-03-20,2025-03-23
26,6836,287,0,534,-,-,Published,DidNotEnter,0,None,SES,Mārtinš SESKS,Rallye Monte-Carlo,2025-01-23,2025-01-26
27,6703,287,0,534,6 + 0,7,Published,Finished,6,None,MCE,Joshua MCERLEAN,Rallye Monte-Carlo,2025-01-23,2025-01-26
28,6703,287,0,536,1 + 1,10,Published,Finished,2,None,MCE,Joshua MCERLEAN,Safari Rally Kenya,2025-03-20,2025-03-23
29,6703,287,0,535,0 + 0,46,Published,Finished,0,None,MCE,Joshua MCERLEAN,Rally Sweden,2025-02-13,2025-02-16
30,6839,287,0,536,4 + 0,8,Published,Finished,4,None,SER,Jourdan SERDERIDIS,Safari Rally Kenya,2025-03-20,2025-03-23
31,6839,287,0,534,-,-,Published,DidNotEnter,0,None,SER,Jourdan SERDERIDIS,Rallye Monte-Carlo,2025-01-23,2025-01-26
32,6839,287,0,535,0 + 0,33,Published,Finished,0,None,SER,Jourdan SERDERIDIS,Rally Sweden,2025-02-13,2025-02-16
33,6987,287,0,536,2 + 0,9,Published,Finished,2,None,ZAL,Fabrizio ZALDIVAR,Safari Rally Kenya,2025-03-20,2025-03-23
34,6987,287,0,534,-,-,Published,DidNotEnter,0,None,ZAL,Fabrizio ZALDIVAR,Rallye Monte-Carlo,2025-01-23,2025-01-26
35,6987,287,0,535,-,-,Published,DidNotEnter,0,None,ZAL,Fabrizio ZALDIVAR,Rally Sweden,2025-02-13,2025-02-16
36,6837,287,0,535,2 + 0,9,Published,Finished,2,None,SOL,Oliver SOLBERG,Rally Sweden,2025-02-13,2025-02-16
37,6837,287,0,536,-,-,Published,DidNotEnter,0,None,SOL,Oliver SOLBERG,Safari Rally Kenya,2025-03-20,2025-03-23
38,6837,287,0,534,-,-,Published,DidNotEnter,0,None,SOL,Oliver SOLBERG,Rallye Monte-Carlo,2025-01-23,2025-01-26
39,6838,287,0,535,1 + 0,10,Published,Finished,1,None,KOR,Roope KORHONEN,Rally Sweden,2025-02-13,2025-02-16
40,6838,287,0,536,-,-,Published,DidNotEnter,0,None,KOR,Roope KORHONEN,Safari Rally Kenya,2025-03-20,2025-03-23
41,6838,287,0,534,-,-,Published,DidNotEnter,0,None,KOR,Roope KORHONEN,Rallye Monte-Carlo,2025-01-23,2025-01-26
42,6840,287,0,536,-,-,Published,DidNotEnter,0,None,BER,Lorenzo BERTELLI,Safari Rally Kenya,2025-03-20,2025-03-23
43,6840,287,0,534,-,-,Published,DidNotEnter,0,None,BER,Lorenzo BERTELLI,Rallye Monte-Carlo,2025-01-23,2025-01-26
44,6840,287,0,535,D,D,Published,DidNotStart,0,None,BER,Lorenzo BERTELLI,Rally Sweden,2025-02-13,2025-02-16

In [ ]:
wrc.getChampionshipRounds()

,eventId,countryId,eventProfileId,country,name,slug,location,startDate,finishDate,year,...,clerkOfTheCourse,stewards,templateFilename,locked,public,applyJumpStarts,displayFiaColumns,roundShakedownTimes,shakedownCount,displayLicenseNumber
0,534,147,2,None,Rallye Monte-Carlo,2025-wrc-monte,"Gap, France",2025-01-23,2025-01-26,2025,...,Romain PUGLIESE,Tanja GEILHAUSEN Edoardo DELLEANI ...,results-report-templates/e352213e-0a5d-443f-b9...,0,0,0,0,0,0,0
1,535,215,2,None,Rally Sweden,2025-wrc-sweden,"Umeå, Västerbotten County",2025-02-13,2025-02-16,2025,...,Stig Rune Kjernsli,Mazen Al-Hilli Mathieu Remmerie ...,results-report-templates/99d0742c-4b8a-4bc9-ab...,0,0,0,0,0,0,0
2,536,116,2,None,Safari Rally Kenya,2025-wrc-kenya,Nairobi,2025-03-20,2025-03-23,2025,...,George Mwangi,Tanja Geilhausen Alice Scutellà ...,results-report-templates/fde0030f-74a1-48a6-ba...,0,0,0,0,0,0,0
3,538,209,2,None,Rally Islas Canarias,2025-wrc-canarias,"Las Palmas, Canarias",2025-04-24,2025-04-27,2025,...,None,None,None,0,0,0,0,0,0,0
4,540,178,2,None,Vodafone Rally de Portugal,2025-wrc-portugal,"Matosinhos, Porto",2025-05-15,2025-05-18,2025,...,None,None,None,0,0,0,0,0,0,0
5,542,110,2,None,Rally Italia Sardegna,2025-wrc-italy,"Alghero, Sardinia",2025-06-05,2025-06-08,2025,...,None,None,None,0,0,0,0,0,0,0
6,544,86,2,None,EKO Acropolis Rally Greece,2025-wrc-greece,"Lamia, Central Greece",2025-06-26,2025-06-29,2025,...,None,None,None,0,0,0,0,0,0,0
7,546,70,2,None,Delfi Rally Estonia,2025-wrc-estonia,Tartu,2025-07-17,2025-07-20,2025,...,None,None,None,0,0,0,0,0,0,0
8,547,75,2,None,Secto Rally Finland,2025-wrc-finland,Jyväskylä,2025-07-31,2025-08-03,2025,...,None,None,None,0,0,0,0,0,0,0
9,549,173,2,None,Rally del Paraguay,2025-wrc-paraguay,Itapúa,2025-08-28,2025-08-31,2025,...,None,None,None,0,0,0,0,0,0,0
10,551,45,2,None,Rally Chile Bio Bío,2025-wrc-chile,"Concepción, Biobío",2025-09-11,2025-09-14,2025,...,None,None,None,0,0,0,0,0,0,0
11,553,294,2,None,Central European Rally,2025-wrc-cer,"Bad Griesbach, Germany",2025-10-16,2025-10-19,2025,...,None,None,None,0,0,0,0,0,0,0
12,554,112,2,None,FORUM8 Rally Japan,2025-wrc-japan,"Toyota, Aichi Prefecture",2025-11-06,2025-11-09,2025,...,None,None,None,0,0,0,0,0,0,0
13,555,195,2,None,Rally Saudi Arabia,2025-wrc-saudi-arabia,Bisha,2025-11-27,2025-11-30,2025,...,None,None,None,0,0,0,0,0,0,0

In [13]:
wrc.getChampionshipEntries()

,championshipEntryId,championshipId,personId,entrantId,manufacturerId,tyreManufacturerId,FirstName,LastName,CountryISO3,Manufacturer,TyreManufacturer
0,6697,287,524,None,33,None,Ott,TÄNAK,EST,Hyundai,None
1,6698,287,700,None,84,None,Kalle,ROVANPERÄ,FIN,Toyota,None
2,6699,287,670,None,84,None,Sébastien,OGIER,FRA,Toyota,None
3,6700,287,534,None,84,None,Elfyn,EVANS,GBR,Toyota,None
4,6701,287,4676,None,33,None,Adrien,FOURMAUX,FRA,Hyundai,None
5,6702,287,762,None,33,None,Thierry,NEUVILLE,BEL,Hyundai,None
6,6703,287,5791,None,26,None,Joshua,MCERLEAN,IRL,Ford,None
7,6704,287,4727,None,13,None,Yohan,ROSSEL,FRA,Citroen,None
8,6705,287,17305,None,77,None,Nikolay,GRYAZIN,BUL,Skoda,None
9,6706,287,4068,None,33,None,Eric,CAMILLI,FRA,Hyundai,None
10,6782,287,5280,None,84,None,Sami,PAJARI,FIN,Toyota,None
11,6783,287,5279,None,26,None,Grégoire,MUNSTER,LUX,Ford,None
12,6784,287,785,None,84,None,Takamoto,KATSUTA,JPN,Toyota,None
13,6836,287,3169,None,26,None,Mārtinš,SESKS,LAT,Ford,None
14,6837,287,5357,None,84,None,Oliver,SOLBERG,SWE,Toyota,None
15,6838,287,9102,None,84,None,Roope,KORHONEN,FIN,Toyota,None
16,6839,287,3125,None,26,None,Jourdan,SERDERIDIS,GRE,Ford,None
17,6840,287,774,None,84,None,Lorenzo,BERTELLI,ITA,Toyota,None
18,6985,287,628,None,77,None,Gus,GREENSMITH,GBR,Skoda,None
19,6986,287,4929,None,84,None,Jan,SOLANS,ESP,Toyota,None
20,6987,287,4776,None,77,None,Fabrizio,ZALDIVAR,PAR,Skoda,None

In [14]:
wrc.getChampionshipCountries()

    countryId          name iso2 iso3
0          45         Chile   CL  CHL
1          70       Estonia   EE  EST
2          75       Finland   FI  FIN
3          86        Greece   GR  GRC
4         110         Italy   IT  ITA
5         112         Japan   JP  JPN
6         116         Kenya   KE  KEN
7         147        Monaco   MC  MCO
8         173      Paraguay   PY  PRY
9         178      Portugal   PT  PRT
10        195  Saudi Arabia   SA  SAU
11        209         Spain   ES  ESP
12        215        Sweden   SE  SWE
13        294        Europe   EU  EUR